---
# tasks file for tinaja.ntp-gps
#
- name: Tinajalabs NTP-GPS | Check to see if running under supported Raspbian release
  fail:
    msg: not running on Buster or Stretch.
  when: ( ansible_distribution_release != "stretch" and ansible_distribution_release != "buster" )

# -------------------------------------------------- disable and stop services
#
- name: Tinajalabs NTP-GPS | Make sure hciuart is disabled and stopped
  systemd:
    name: hciuart
    enabled: false
    state: stopped
#
- name: Tinajalabs NTP-GPS | Make sure serial-getty@ttyAMA0.service is disabled and stopped
  systemd:
    name: serial-getty@ttyAMA0.service
    enabled: false
    state: stopped
#
# -------------------------------------------------- update apt and install these packages
#
- name: Tinajalabs NTP-GPS | Updating apt cache
  apt:
    update_cache: yes

- name: Tinajalabs NTP-GPS | Install packages with apt
  apt:
    name: ['ntp', 'pps-tools', 'gpsd', 'gpsd-clients']

- name: Tinajalabs NTP-GPS | Remove unneeded packages with apt
  apt:
    name: [ 'bluez', 'triggerhappy', 'wpasupplicant', 'avahi-daemon' ]
    state: absent
    purge: yes

#
# -------------------------------------------------- update files
#
- name: Tinajalabs NTP-GPS | Update /boot/cmdline.txt
  template:
    src: "{{ lookup('first_found', sources) }}"
    dest: /boot/cmdline.txt
  vars:
    sources:
      - "{{ inventory_dir }}/templates/cmdline.txt.j2"
      - "{{ role_path }}/templates/cmdline.txt.j2"
#
- name: Tinajalabs NTP-GPS | Update /boot/config.txt
  template:
    src: "{{ lookup('first_found', sources) }}"
    dest: /boot/config.txt
  vars:
    sources:
      - "{{ inventory_dir }}/templates/config.txt.j2"
      - "{{ role_path }}/templates/config.txt.j2"
#
- name: Tinajalabs NTP-GPS | Update /etc/dhcp/dhclient.conf
  template:
    src: "{{ lookup('first_found', sources) }}"
    dest: /etc/dhcp/dhclient.conf
  vars:
    sources:
      - "{{ inventory_dir }}/templates/dhclient.conf.j2"
      - "{{ role_path }}/templates/dhclient.conf.j2"
#
- name: Tinajalabs NTP-GPS | Update /etc/default/gpsd
  template:
    src: "{{ lookup('first_found', sources) }}"
    dest: /etc/default/gpsd
  vars:
    sources:
      - "{{ inventory_dir }}/templates/gpsd.j2"
      - "{{ role_path }}/templates/gpsd.j2"
#
- name: Tinajalabs NTP-GPS | Update /etc/ntp.conf
  template:
    src: "{{ lookup('first_found', sources) }}"
    dest: /etc/ntp.conf
  vars:
    sources:
      - "{{ inventory_dir }}/templates/ntp.conf.j2"
      - "{{ role_path }}/templates/ntp.conf.j2"
#
# -------------------------------------------------- delete files
#
- name: Tinajalabs NTP-GPS - Delete unneeded files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/dhcp/dhclient-exit-hooks.d/ntp
    - /lib/dhcpcd/dhcpcd-hooks/50-ntp.conf
    - /var/lib/ntp/ntp.conf.dhcp
#
# -------------------------------------------------- log files and directories happy
#
- name: Tinajalabs NTP-GPS - /var/lib/ntp/ exists and is in good shape
  file:
    path: /var/lib/ntp
    state: directory
    owner: ntp
    group: ntp
    mode: 0755
#
- name: Tinajalabs NTP-GPS - /var/lib/ntp/ntp.drift exists and is in good shape
  file:
    path: /var/lib/ntp/ntp.drift
    state: touch
    owner: ntp
    group: ntp
    mode: 0644
#
# -------------------------------------------------- restart services
#
- name: Tinajalabs NTP-GPS - Make sure dhcp is restarted and running
  systemd:
    name: dhcpcd
    daemon_reload: true
    enabled: true
    state: restarted
#
- name: Tinajalabs NTP-GPS - Make sure ntp is restarted and running
  systemd:
    name: ntp
    daemon_reload: true
    enabled: true
    state: restarted
#
- name: Tinajalabs NTP-GPS - Make sure gpsd is restarted and running
  systemd:
    name: gpsd
    daemon_reload: true
    enabled: true
    state: restarted
